# Generated by Django 5.2.3 on 2025-06-13 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('progress', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='progressprofile',
            name='current_level',
            field=models.IntegerField(default=0),
        ),
    ]
