# Generated by Django 5.2.3 on 2025-06-15 08:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('progress', '0002_alter_progressprofile_current_level'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userachievement',
            options={'ordering': ['-unlocked_at']},
        ),
        migrations.AddField(
            model_name='progressprofile',
            name='total_early_completions',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='progressprofile',
            name='total_late_completions',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='progressprofile',
            name='total_on_time_completions',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='progressprofile',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.CreateModel(
            name='WeeklyReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week_start', models.DateField()),
                ('week_end', models.DateField()),
                ('total_tasks', models.IntegerField(default=0)),
                ('total_xp', models.IntegerField(default=0)),
                ('early_completions', models.IntegerField(default=0)),
                ('on_time_completions', models.IntegerField(default=0)),
                ('late_completions', models.IntegerField(default=0)),
                ('performance_score', models.IntegerField(default=0)),
                ('suggestions', models.TextField(blank=True)),
                ('category_breakdown', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weekly_reviews', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-week_start'],
                'unique_together': {('user', 'week_start')},
            },
        ),
    ]
