# Generated by Django 5.2.3 on 2025-07-15 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('progress', '0005_notificationtype_systemsetting_leaderboardtype_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermission',
            name='is_completed',
            field=models.BooleanField(default=False),
        ),
    ]
