# Generated by Django 5.2.3 on 2025-07-16 08:02

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('progress', '0006_usermission_is_completed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='systemsetting',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
