# Generated by Django 5.2.3 on 2025-07-16 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('progress', '0007_alter_systemsetting_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='systemsetting',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
