# Generated by Django 5.2.3 on 2025-07-16 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('progress', '0008_alter_systemsetting_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weeklyreview',
            name='suggestions',
            field=models.TextField(blank=True, default=''),
        ),
    ]
