# Generated by Django 5.2.3 on 2025-07-16 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('progress', '0009_alter_weeklyreview_suggestions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weeklyreview',
            name='performance_score',
            field=models.FloatField(default=0),
        ),
    ]
