# Generated by Django 5.2.3 on 2026-05-09 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('progress', '0010_alter_weeklyreview_performance_score'),
    ]

    operations = [
        migrations.AlterField(
            model_name='xplog',
            name='action',
            field=models.CharField(choices=[('task_complete', 'Task Completion'), ('streak_bonus', 'Streak Bonus'), ('achievement', 'Achievement Unlock'), ('daily_login', 'Daily Login'), ('bonus', 'Manual Bonus'), ('mission_complete', 'Mission Completion')], max_length=20),
        ),
    ]
