# Generated by Django 5.2.3 on 2026-05-09 17:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('progress', '0011_alter_xplog_action'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermission',
            name='template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='progress.missiontemplate'),
        ),
    ]
