# Generated by Django 5.2.3 on 2026-05-09 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('progress', '0012_alter_usermission_template'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermission',
            name='mission_type',
            field=models.CharField(blank=True, choices=[('task_count', 'Complete X Tasks'), ('category_focus', 'Complete X Tasks in Category'), ('streak', 'Maintain X Day Streak'), ('timing', 'Complete X Tasks Early/On Time'), ('difficulty', 'Complete X Hard/Expert Tasks'), ('xp_target', 'Earn X XP'), ('daily_goal', 'Complete Daily Goal'), ('weekly_challenge', 'Weekly Challenge')], default='task_count', max_length=20, null=True),
        ),
    ]
