# Generated by Django 5.2.3 on 2026-05-09 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_customuser_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useractivity',
            name='activity_type',
            field=models.CharField(choices=[('login', 'Login'), ('logout', 'Logout'), ('registration', 'Registration'), ('profile_update', 'Profile Update'), ('profile_view', 'Profile Viewed'), ('password_change', 'Password Change'), ('password_reset', 'Password Reset'), ('email_change', 'Email Change'), ('avatar_update', 'Avatar Update')], max_length=50),
        ),
    ]
